name: debug

on:
  workflow_dispatch:


jobs:
  debug:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Setup Debug Session
        uses: eyu-dev/debugger-action@master